name: CI # name of the git actions Workflow 

on:
  push: # using push like so (with :) makes it a blocker meaning not on every push but only on pushed to main
    branches: [master]
  pull_request:

jobs: # list of jobs
  test: # one job named test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code # name of the tasks to perform (like a description) 
        uses: actions/checkout@v4 # @v4 means major version.

      - name: Set up Python
        uses: actions/setup-python@v5
        with: # is passing parameter to the action (like vargin or function inputs)
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint
        run: ruff check .

      - name: Run tests
        run: pytest -v